apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret-db
  namespace: db
type: Opaque
data:
  # TODO: マニフェストファイルにシークレット情報を記載しない方法に修正
  root_password: cm9vdHBhc3M= #value=rootpass
  user: bXlzcWx1c2Vy #value=mysqluser
  password: bXlzcWx1c2VycGFzcw== #value=mysqluserpass
  database_name: c2FtcGxlZGI= #value=sampledb
---

apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret-app
  namespace: app
type: Opaque
data:
  # TODO: マニフェストファイルにシークレット情報を記載しない方法に修正
  root_password: cm9vdHBhc3M= #value=rootpass
  user: bXlzcWx1c2Vy #value=mysqluser
  password: bXlzcWx1c2VycGFzcw== #value=mysqluserpass
  database_name: c2FtcGxlZGI= #value=sampledb