apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  namespace: app
spec:
  type: ClusterIP
  selector:
    app: springboot
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-deployment
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: springboot
        image: ghcr.io/ta8i2chi8/spring-boot:latest
        env:
          # Use secret in real usage
        - name: DB_URL
          value: jdbc:mysql://mysql-service.db.svc.cluster.local:3306
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret-app
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret-app
              key: password
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret-app
              key: database_name
        ports:
        - containerPort: 8080
          name: springboot-port
        resources: 
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
      # imagePullSecrets:
      #   - name: ghcr-login-secret