#######################################################################
# Spring Boot Built-in
#######################################################################
server:
  port: 8080

#######################################################################
# Spring Setting
#######################################################################
spring:
  application:
    name: hello-world
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306}/${DB_DATABASE:sampledb}
    username: ${DB_USER:dev_user}
    password: ${DB_PASSWORD:dev_user_pass}

#######################################################################
# MyBatis Setting
#######################################################################
mybatis:
  configuration:
    map-underscore-to-camel-case: true

#######################################################################
# log Setting
#######################################################################
logging:
  level:
    org:
      springframework:
        security: DEBUG